name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ACCOUNT_NAME: cluster_account_name

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Formatting
      uses: github/super-linter@v6
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/config/config.yaml --executor local --lint"

  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Linting
      - Formatting
    steps:
    - name: Checkout test
      uses: actions/checkout@v4

    - name: Setup credentials to access private repositories
        run: git config --global url.https://${{ secrets.ACCESS_BBQ_THROUGH_PIPELINE }}@github.com/.insteadOf https://github.com/
    - name: Test workflow
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--directory .test --executor local --software-deployment-method conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache --all-temp"
    - name: Test report
      uses: snakemake/snakemake-github-action@v1.25.1
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--directory .test --report report.html"